name: SonarQube Scan Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: '.'
          token: f1d1fdafd3876b80f26196483d383249dae3208c
          base: main
    
#   sonar:
#     name: SonarQube Scan
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
        
#       - name: SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v1.1.0       
#         with:
#           args: >
#             -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
#             -Dsonar.projectName=${{ secrets.SONAR_PROJECT_NAME }}
#             -Dsonar.verbose=true
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
